# Databricks notebook source
# MAGIC %md
# MAGIC # CosmosGenie — Gradio App
# MAGIC Astronomy intelligence assistant powered by Genie Agent on Databricks.
# MAGIC Deploy this file as a Databricks App from the cosmosgenie/ folder.

# COMMAND ----------

import gradio as gr
import os
import re
import time
import requests as http
from databricks.sdk import WorkspaceClient

# ── Config ────────────────────────────────────────────────────────────
GENIE_SPACE_ID = os.environ.get("GENIE_SPACE_ID", "")
DASHBOARD_URL  = os.environ.get("DASHBOARD_URL",  "")
w = WorkspaceClient()

# ── Genie Query with Reasoning Chain ──────────────────────────────────
def query_genie(question: str) -> tuple:
    """
    Returns (answer_with_reasoning_markdown, sql_used).
    Prepends a reasoning chain showing tables queried, SQL generated,
    and row count — surfacing Genie transparency in the chat response.
    """
    if not GENIE_SPACE_ID:
        return "⚠️ GENIE_SPACE_ID not configured in app.yaml.", ""
    try:
        conv = w.genie.start_conversation(space_id=GENIE_SPACE_ID, content=question)
        c_id = conv.conversation_id
        m_id = conv.message_id

        for _ in range(90):          # poll up to 90 s
            msg = w.genie.get_message(GENIE_SPACE_ID, c_id, m_id)
            if str(msg.status).split(".")[-1] in ("COMPLETED", "FAILED", "CANCELLED"):
                break
            time.sleep(1)

        answer, sql, row_count = "", "", None
        if msg.attachments:
            for att in msg.attachments:
                if hasattr(att, "text") and att.text:
                    answer += att.text.content + "\n\n"
                if hasattr(att, "query") and att.query:
                    sql = att.query.query or ""
                    if hasattr(att.query, "rows") and att.query.rows:
                        row_count = len(att.query.rows)

        # Build reasoning chain prefix
        reasoning = ""
        if sql:
            tables = list(dict.fromkeys(
                t for pair in re.findall(r'(?:FROM|JOIN)\s+([\w.]+)', sql, re.IGNORECASE)
                for t in [pair] if t
            ))
            table_str = ", ".join(f"`{t}`" for t in tables) if tables else "`cosmos.space.*`"
            rows_str  = f"{row_count} rows" if row_count is not None else "results"
            reasoning = (
                f"🔍 **Tables queried:** {table_str}  \n"
                f"⚡ **{rows_str} returned**\n\n"
                f"<details><summary>⚙️ *View SQL generated by Genie*</summary>\n\n"
                f"```sql\n{sql}\n```\n\n</details>\n\n---\n\n"
            )

        final = answer.strip() or "No results found. Try rephrasing your question."
        return reasoning + final, sql

    except Exception as e:
        return f"❌ Error: {str(e)}", ""

# ── Mission Control helpers ────────────────────────────────────────────
def fetch_live_news(limit=5):
    try:
        return http.get(
            f"https://api.spaceflightnewsapi.net/v4/articles/?limit={limit}&ordering=-published_at",
            timeout=8
        ).json().get("results", [])
    except:
        return []

def fetch_upcoming_launches(limit=8):
    try:
        return http.get(
            "https://ll.thespacedevs.com/2.2.0/launch/upcoming/?limit=8&format=json",
            timeout=10
        ).json().get("results", [])
    except:
        return []

def render_mission_control():
    news     = fetch_live_news(5)
    launches = fetch_upcoming_launches(8)

    # CSS ticker (replaces deprecated <marquee>)
    ticker_items = " &nbsp;►&nbsp; ".join(
        f'<a href="{a["url"]}" target="_blank" style="color:#6495ed">{a["title"]}</a>'
        for a in news
    )
    ticker_html = f"""
    <div style='background:rgba(255,149,0,0.06);border:1px solid rgba(255,149,0,0.2);
                border-radius:8px;padding:10px 14px;margin-bottom:16px;'>
      <span style='font-size:10px;color:#ff9500;font-weight:700;text-transform:uppercase;
                   letter-spacing:1px;margin-right:12px;'>⚡ Breaking Space News</span>
      <div style='overflow:hidden;'>
        <div style='display:inline-block;white-space:nowrap;
                    animation:tickscroll 45s linear infinite;padding-left:100%;'>
          {ticker_items}
        </div>
      </div>
      <style>@keyframes tickscroll{{0%{{transform:translateX(0)}}100%{{transform:translateX(-100%)}}}}</style>
      <div style='font-size:10px;color:#3a5080;margin-top:6px;'>
        Live from Spaceflight News API · Refreshed every 6 hours
      </div>
    </div>"""

    rows = ""
    for L in launches:
        net    = (L.get("net") or "")[:10]
        name   = (L.get("name") or "")[:50]
        agency = ((L.get("launch_service_provider") or {}).get("name") or "")[:25]
        status = (L.get("status") or {}).get("name", "")
        rocket = ((L.get("rocket") or {}).get("configuration") or {}).get("name", "") or ""
        desc   = ((L.get("mission") or {}).get("description") or "").lower()
        mtype  = ((L.get("mission") or {}).get("type") or "").lower()
        badges = (" 🌕" if any(w in desc for w in ["moon","lunar","artemis"]) else "") + \
                 (" 👨\u200d🚀" if mtype in ("human exploration","crewed") else "")
        sc = "#6bcb77" if status == "Go" else "#ff9500" if status == "TBD" else "#a8c0f0"
        rows += f"""<tr>
          <td style='padding:7px 10px;color:#7090c0;font-size:11px;'>{net}</td>
          <td style='padding:7px 10px;color:#d0e0ff;font-size:12px;font-weight:600;'>{name}{badges}</td>
          <td style='padding:7px 10px;color:#8aaedc;font-size:11px;'>{agency}</td>
          <td style='padding:7px 10px;'><span style='color:{sc};font-weight:700;font-size:11px;'>{status}</span></td>
          <td style='padding:7px 10px;color:#5a7acc;font-size:11px;'>{rocket}</td></tr>"""

    launches_html = f"""
    <div style='font-size:10px;color:#4a6aaa;text-transform:uppercase;font-weight:700;
                margin-bottom:10px;letter-spacing:1.5px;'>🚀 Upcoming Launches</div>
    <div style='border-radius:8px;overflow:hidden;border:1px solid rgba(100,149,237,0.14);'>
      <table style='width:100%;border-collapse:collapse;font-family:inherit;'>
        <thead><tr style='background:rgba(100,149,237,0.12);'>
          <th style='padding:7px 10px;text-align:left;color:#4a6aaa;font-size:10px;text-transform:uppercase;'>Date</th>
          <th style='padding:7px 10px;text-align:left;color:#4a6aaa;font-size:10px;text-transform:uppercase;'>Mission</th>
          <th style='padding:7px 10px;text-align:left;color:#4a6aaa;font-size:10px;text-transform:uppercase;'>Agency</th>
          <th style='padding:7px 10px;text-align:left;color:#4a6aaa;font-size:10px;text-transform:uppercase;'>Status</th>
          <th style='padding:7px 10px;text-align:left;color:#4a6aaa;font-size:10px;text-transform:uppercase;'>Rocket</th>
        </tr></thead>
        <tbody style='background:rgba(10,22,46,0.8);'>{rows}</tbody>
      </table>
    </div>
    <div style='font-size:10px;color:#2e4068;margin-top:8px;font-style:italic;'>
      🌕 = Moon mission &nbsp; 👨\u200d🚀 = Crewed &nbsp;·&nbsp; Data: The Space Devs · Spaceflight News API
    </div>"""
    return ticker_html + launches_html

# ── Quick questions ────────────────────────────────────────────────────
QUICK = [
    ("☄️ Asteroids this week",     "Are there any asteroids approaching Earth in the next 7 days?"),
    ("🔴 Next blood moon",          "When is the next blood moon and where can it be seen?"),
    ("🌑 Next solar eclipse",       "When is the next total solar eclipse and where?"),
    ("🪐 Planetary alignments",     "What planetary conjunctions are coming up in the next 6 months?"),
    ("☀️ Solar flares",             "What are the strongest solar flares recorded this month?"),
    ("🌠 Best meteor shower next",  "What meteor shower peaks next and how many meteors per hour?"),
    ("⚠️ Hazardous asteroids",      "How many potentially hazardous asteroids are in the database?"),
]

KID_SUFFIX = (
    " — please explain this to a curious 10-year-old. "
    "Use simple words, fun comparisons (like school buses for size, "
    "football fields for distance), and end with one amazing fun fact."
)

# ── CSS ────────────────────────────────────────────────────────────────
CSS = """
.gradio-container { background: #050d1a !important; color: #e8f0fe !important; }
footer { display: none !important; }
.kpi-row { display:flex; gap:10px; margin:10px 0; }
.kpi-box { flex:1; background:rgba(100,149,237,0.08); border:1px solid rgba(100,149,237,0.2);
           border-radius:10px; padding:12px; text-align:center; }
.kpi-val  { font-size:22px; font-weight:800; color:#6495ed; }
.kpi-lbl  { font-size:10px; color:#4a6aaa; text-transform:uppercase; margin-top:4px; }
button.quick-btn { background:rgba(100,149,237,0.1) !important;
                   border:1px solid rgba(100,149,237,0.25) !important;
                   color:#8aaedc !important; border-radius:20px !important;
                   font-size:12px !important; }
"""

# ── Build UI ───────────────────────────────────────────────────────────
with gr.Blocks(css=CSS, title="CosmosGenie") as demo:

    gr.HTML("""
    <div style='text-align:center;padding:20px 0 6px'>
      <h1 style='font-size:2em;background:linear-gradient(135deg,#6495ed,#b19cd9,#ff9500);
                  -webkit-background-clip:text;-webkit-text-fill-color:transparent;'>
        🔭 CosmosGenie</h1>
      <p style='color:#4a6aaa;font-size:13px;'>
        Your universe, answered · Powered by Genie Agent on Databricks</p>
    </div>""")

    gr.HTML("""
    <div class='kpi-row'>
      <div class='kpi-box'><div class='kpi-val'>—</div><div class='kpi-lbl'>☄️ Asteroids this week</div></div>
      <div class='kpi-box'><div class='kpi-val' style='color:#ff6b6b'>—</div><div class='kpi-lbl'>⚠️ Potentially Hazardous</div></div>
      <div class='kpi-box'><div class='kpi-val' style='color:#b19cd9'>—</div><div class='kpi-lbl'>🌙 Moon Phase</div></div>
      <div class='kpi-box'><div class='kpi-val' style='color:#ff9500'>—</div><div class='kpi-lbl'>☀️ Space Weather</div></div>
      <div class='kpi-box'><div class='kpi-val'>—</div><div class='kpi-lbl'>🔭 Days to Eclipse</div></div>
      <div class='kpi-box'><div class='kpi-val' style='color:#6bcb77'>—</div><div class='kpi-lbl'>🪐 Days to Alignment</div></div>
    </div>""")

    with gr.Tabs():

        with gr.TabItem("🔭 Ask CosmosGenie"):
            with gr.Row():
                for label, _ in QUICK:
                    gr.Button(label, elem_classes="quick-btn", size="sm")

            chatbot = gr.Chatbot(
                value=[[None, "Hi! I'm CosmosGenie 🌌 Ask me anything about asteroids, "
                        "eclipses, blood moons, planetary alignments, missions or space weather "
                        "— all backed by real NASA and USNO data."]],
                height=450, type="tuples",
                avatar_images=(None, "https://em-content.zobj.net/source/apple/391/telescope_1f52d.png")
            )
            with gr.Row():
                msg_box = gr.Textbox(
                    placeholder="Ask about asteroids, eclipses, blood moons, launches...",
                    show_label=False, scale=8
                )
                kid_mode = gr.Checkbox(label="🧒 Kid Mode", value=False, scale=1)
                send_btn = gr.Button("Ask ›", scale=1, variant="primary")

            def make_handler(q):
                def handler(history, km):
                    actual_q = q + KID_SUFFIX if km else q
                    answer, _ = query_genie(actual_q)
                    if km:
                        answer = "🧒 **Kid Mode**\n\n" + answer
                    history = history or []
                    history.append([q, answer])
                    return history, ""
                return handler

            for (label, question), btn in zip(QUICK, demo.blocks[gr.Button]):
                btn.click(make_handler(question), inputs=[chatbot, kid_mode], outputs=[chatbot, msg_box])

            def chat(message, history, km):
                history = history or []
                actual_q = message + KID_SUFFIX if km else message
                answer, _ = query_genie(actual_q)
                if km:
                    answer = "🧒 **Kid Mode**\n\n" + answer
                history.append([message, answer])
                return history, ""

            send_btn.click(chat, inputs=[msg_box, chatbot, kid_mode], outputs=[chatbot, msg_box])
            msg_box.submit(chat, inputs=[msg_box, chatbot, kid_mode], outputs=[chatbot, msg_box])

        with gr.TabItem("📊 Tonight's Sky"):
            if DASHBOARD_URL:
                gr.HTML(f'<iframe src="{DASHBOARD_URL}" width="100%" height="720px" '
                        f'frameborder="0" style="border-radius:10px;margin-top:10px"></iframe>')
            else:
                gr.Markdown("*Set `DASHBOARD_URL` in `app.yaml` to embed the AI/BI Dashboard here.*")

        with gr.TabItem("🚀 Mission Control"):
            mc_html = gr.HTML(render_mission_control())
            with gr.Row():
                mc_refresh = gr.Button("🔄 Refresh", size="sm", scale=0)
                gr.Markdown("*Click any headline, paste into Ask tab — Genie gives the full story.*", scale=5)
            mc_refresh.click(render_mission_control, outputs=mc_html)

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=8080)
